# Generated by Django 3.1 on 2020-08-10 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_label', '0002_blogpost_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Post',
        ),
    ]
