# Generated by Django 3.1 on 2020-08-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_label', '0004_auto_20200810_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
