# Generated by Django 3.1 on 2020-08-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_label', '0005_auto_20200810_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='edition',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='release',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
