# Generated by Django 3.1 on 2020-08-11 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_label', '0007_release_cover_art'),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='short_name',
            new_name='cat_no',
        ),
        migrations.RenameField(
            model_name='release',
            old_name='long_name',
            new_name='name',
        ),
    ]
