# Generated by Django 3.1 on 2020-08-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_label', '0008_auto_20200811_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
