# Generated by Django 3.1 on 2020-08-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_label', '0009_auto_20200814_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='release',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
