# Generated by Django 3.1 on 2020-09-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_label', '0011_auto_20200817_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='audio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
