# Generated by Django 3.1 on 2020-09-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_label', '0012_release_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
