# Generated by Django 3.1 on 2020-09-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_label', '0013_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.TextField(),
        ),
    ]
